### ISSUE TITLE
Compatibility Issues with v2.2.2

### ISSUE THREAD

**Issue by Jiroga** [Sulayre/WebfishingLure#1]
**What's up:** After updating to the newest version (v2.2.2), the game will refuse to load saves due to compatibility issues, namely when having [NeoQOLPack](https://github.com/neomoth/NeoQOLPatchMod) installed. Additionally, mods that depend on _WebfishingLure_ no longer load, such as [RayTrac3rs's Cosmetics](https://github.com/RAYTRAC3R/RAYTRAC3R-s-Cosmetics).

Downgrading back to 2.2.1 fixes any issues encountered.

Steps to Reproduce:
1. Install WebfishingLure, RayTrac3r's Cosmetics, and NeoQOLPack through HLS.
2. Start game.
3. Game will refuse to load a save.
4. Do any of the following:
    - Disable either WebfishingLure & RayTrac3r's Cosmetics through HLS.
    - Disable NeoQOLPack through HLS.
    - Revert WebfishingLure back to v2.2.1 through _3rd Party Mods_ option in HLS.
5. Start game (again).
6. Game will load a save normally.

I am not aware if the changes made in v2.2.2 would have any reason to create compatibility issues based on the given update logs (perhaps due to the way the mod handles certain things now compared to previously?), but I thought you might like to know what's happening!

**Comment by GXyon** [comment]
Update: After a complete uninstallation and reinstall of WebfishingLure, it seems to work now with dependent mods regardless of version! However, the inability to load a save when NeoQOLPack is installed alongside it is still there.

**Comment by Jiroga** [comment]
Update: As of the last hotfix, this particular issue seems to have been fully resolved. 👍
