### ISSUE TITLE
Custom props not being despawned when player leaves server

### ISSUE THREAD

**Issue by ThePotato97** [Sulayre/WebfishingLure#12]
For some reason when the player leaves the server my custom prop isn't despawning (maybe I broke something)

Here's how I'm initializing the custom prop:
https://github.com/ThePotato97/PotatoRadio/blame/0dfad03e489673c2d1f347fff0b235ae2ebe4001/main.gd#L48

**Comment by Sulayre** [comment]
not sure how to test this potato cus your radio mod doesn't even work on my archlinux :sob: i'll try to replicate the issue but i can't promise anything hmu on the modding discord if you wanna look into figuring it out

**Comment by yungnickyoung** [comment]
![image](https://github.com/user-attachments/assets/43eeb919-d5ff-4aa9-8782-8edf0b612ce8)
on your root node with the prop.gd script attached, did you check this box?

**Comment by ThePotato97** [comment]
Probably fixed, I have no way to test
