### ISSUE TITLE
Adding a custom fish to the metal pool makes collector rods unobtainable

### ISSUE THREAD

**Issue by SCAbruh** [Sulayre/WebfishingLure#13]
I made a personal mod that simply adds one fish to the metal pool for the metal detector, and caught every radiant fish, and the game wouldn't give me the quest until I disabled the mod I made.

I presume the game is expecting me to catch the custom fish as a radiant as well, but since it's obtained through the metal detector, that is impossible.

**Comment by Sulayre** [comment]
aware of this issue, forgot to log it in the todo list, not a high priority atm
