### ISSUE TITLE
Newest game version causes Lure to crash on bootup

### ISSUE THREAD

**Issue by Dogeisbest** [Sulayre/WebfishingLure#18]
Frame one new issue

**Comment by Sulayre** [comment]
working on it

**Comment by heikadog** [comment]
still crashes as of newest lure update

**Comment by Dogeisbest** [comment]
sorry forgot to update but it doesn't crash anymore--at least for me
one thing that _was_ crashing my game was Lure + LucysTools & NeosQOL, so I'd definitely check those off first if you have them installed @heikadog
