### ISSUE TITLE
Lure causes new misc fish to not be visible in journal

### ISSUE THREAD

**Issue by SlimeProgenitor** [Sulayre/WebfishingLure#22]
running Lure v4.1.0 downloaded from thunderstore via HLS mod manager with webfishing v1.09

the journal entry for the new misc tab fish (CREATURE) in 1.09 is missing when Lure is installed. Running the game without Lure causes the entry to return and displays correct stats/information.

**Comment by Hackstr0** [comment]
Can confirm this is an issue as well

**Comment by Hackstr0** [comment]
has this been fixed as of 4.2.0? i dont want to load my save until i know for sure

**Comment by SlimeProgenitor** [comment]
It is fixed as of 4.2.0
