### ISSUE TITLE
All Cosmetics Show As New

### ISSUE THREAD

**Issue by RickyTheRacc** [Sulayre/WebfishingLure#23]
Happens after every game launch, only with Lure installed, random items seem to be marked as "new". You can get rid of the labels by mousing over them like normal but in order to update the tabs you have to reopen the backpack screen, and the new label on the overall cosmetics tab never goes away, even if there are no new items left.
![image](https://github.com/user-attachments/assets/2f71c205-e817-4744-9aaf-5b5d69409518)

**Comment by SlimeProgenitor** [comment]
this is not exclusive to lure based cosmetic mods, all modded cosmetics do this. There's a mod on thunderstore called "New Icon Removed" which solves this problem by removing the new icon.

**Comment by RickyTheRacc** [comment]
Well yes but I'm showing here that it's happening even to non-modded cosmetics, those eyes there are all from the base game and I've unlocked them a decent while back. I did find the mod but I think the issue itself is still worth looking into, since I did appreciate having the new thing when it worked correctly

**Comment by Sulayre** [comment]
should be fixed as of 4.2.0, submit again of it happens once more
