### ISSUE TITLE
Lure is still broken on hook line n sinker

### ISSUE THREAD

**Issue by Fiji-Krowe** [Sulayre/WebfishingLure#26]
I've tried everything, downloading from github, from thunderstore, from the manager itself but lure just keeps crashing GDWeave. Is it a problem with me orrr...??

Like every other mod works fine, it's just the moment I put lure in, it crashes.

**Comment by Sulayre** [comment]
can you provide a list of mods you're playing with aside from lure? can't replicate nor figure it out if you don't attach a log or a save file with your issue.
