### ISSUE TITLE
No rainclouds spawn with Lure 2.2.0 and above

### ISSUE THREAD

**Issue by Vonkie** [Sulayre/WebfishingLure#4]
I noticed a lack of rainclouds for a while now, testing confirmed that having Lure installed, even on it's own, appears to be the cause.
Testing previous versions I can trace back this issue to 2.2.0, any version prior to that does not have this issue.

The most obvious give away of the issue is the fact that the rain chance does not appear to increase in the log file: `%APPDATA%\Godot\app_userdata\webfishing_2_newver\logs\godot.log`

In this file you'll find lines looking as followed: `Spawning Object, Type: none (rain: #.####%)` the #.#### representing the current rain chance. This number should increase almost every time the line(every 10 seconds) appears normally (75% chance to increase.)

However, with Lure 2.2.0+ the chance remains the same regardless of how much time passed.

I've tested this on a clean save, and obviously without other mods installed and GDWeave v2.0.10
I have not delved into the source to see what might be the issue.

**Comment by Sulayre** [comment]
no idea what's causing this in the slightest, gonna look into it, apologies for the inconvenience.

**Comment by Vonkie** [comment]
No worries, just noticed the lack of rain for a while and was confused.
Not sure where Lure would be affecting this part of the game, but according to the [wiki](https://webfishing.wiki.gg/wiki/Events) here, this loop is probably also the one that affects ripples and meteor spawns. And events get overridden by any event that also fits in this loop *after* the rain event.

So if there is any code that adds any sort of event or in any way utilizes that 10 second timer, you might be overriding the rain chance increase?

Just a suggestion of what could be a potential cause, I haven't looked into modding for the game myself, so I'm not exactly familiar with the game loops yet.

**Comment by Sulayre** [comment]
try with 3.1.0, hopefully its solved now

**Comment by Vonkie** [comment]
I'm afraid it doesn't appear to be, when starting the game with no mods other than Lure 3.1.0 (and GDWeave) the rain chance percentage still does not increase as expected, according to the log file.

Is this exclusive to my game? It still seemed to happen on a new save...

**Comment by Vonkie** [comment]
Never mind, I didn't noticed GDWeave had an update too, with the latest GDWeave version, it seems to be fixed.
I'm guessing it was the floating point bug they mention there, rather than an issue with Lure

Thank you! and sorry for the confusion.
