### ISSUE TITLE
stuck on lobby loading screen

### ISSUE THREAD

**Issue by leapfroggrr** [Sulayre/WebfishingLure#6]
MADE A GITHUB JUST FOR THIS,, i get stuck on the loading screen whenever i join a lobby when i have lure installed! it doesnt seem to matter what version, am i doing something wrong?
![Screenshot 2024-10-28 160527](https://github.com/user-attachments/assets/1df0ae06-b7de-4ecd-80f0-3c9dbf148e61)

**Comment by Sulayre** [comment]
make a new file called ``override.cfg``, add it to the game's exe folder
write this inside of it and save
    [logging]
    file_logging/enable_file_logging = true
    file_logging/log_path = "log.txt"
open the game and when it crashes a ``log.txt`` file will show up
send the file here

**Comment by leapfroggrr** [comment]
i shouldve been more specific, my game doesnt crash. it just gets stuck on loading when joining a lobby! sorry for the trouble

**Comment by ombwie** [comment]
hello! im also having this issue. here is my log file. i alt f4ed after about 2 mins of the infinite loading screen. ill also attach a pic of my mods folder
[log.txt](https://github.com/user-attachments/files/17549885/log.txt)
[mods](https://github.com/user-attachments/assets/7bb21fdb-6ec9-476e-b1ce-afa42163cd2b)

**Comment by leapfroggrr** [comment]
it seems like using ver 2.1 fixes it and gets cosmetics to work, thats weird

**Comment by Sulayre** [comment]
> hello! im also having this issue. here is my log file. i alt f4ed after about 2 mins of the infinite loading screen. ill also attach a pic of my mods folder
> 
> [log.txt](https://github.com/user-attachments/files/17549885/log.txt)
> 
> [mods](https://github.com/user-attachments/assets/7bb21fdb-6ec9-476e-b1ce-afa42163cd2b)
> 
> 

seems like day/night lonelyloner mod is crashing the game, doesnt seem to be a lure issue, heard this before gonna look into it

**Comment by leapfroggrr** [comment]
weirdly enough i dont have that mod. this is my list
![Screenshot 2024-10-28 222528](https://github.com/user-attachments/assets/2ddfcff7-ef32-4428-9110-32b88fb8a66f)

**Comment by Vonkie** [comment]
@leapfroggrr and @ombwie 
update [NeoQOLPack](https://github.com/neomoth/NeoQOLPatchMod) to the latest version if it isn't already, I've had this issue happen with an older version of that mod.

**Comment by leapfroggrr** [comment]
thank you!
